kind: Entity
apiVersion: v1
metadata:
  name: role
spec:
  schema:
    ref:
      - account
      - jadoo
  attributes:
    - name: id
      type: UUID
      isPrimary: true
    - name: flags
      type: Int8
